[2023-07-27T03:30:30.996+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgresv03.get_s3_id manual__2023-07-27T03:25:14.565202+00:00 [queued]>
[2023-07-27T03:30:31.002+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgresv03.get_s3_id manual__2023-07-27T03:25:14.565202+00:00 [queued]>
[2023-07-27T03:30:31.002+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 7
[2023-07-27T03:30:31.012+0000] {taskinstance.py:1327} INFO - Executing <Task(S3KeySensor): get_s3_id> on 2023-07-27 03:25:14.565202+00:00
[2023-07-27T03:30:31.015+0000] {standard_task_runner.py:57} INFO - Started process 225 to run task
[2023-07-27T03:30:31.018+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_postgresv03', 'get_s3_id', 'manual__2023-07-27T03:25:14.565202+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_dependency.py', '--cfg-path', '/tmp/tmp2t8cd1rf']
[2023-07-27T03:30:31.021+0000] {standard_task_runner.py:85} INFO - Job 18: Subtask get_s3_id
[2023-07-27T03:30:31.062+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_with_postgresv03.get_s3_id manual__2023-07-27T03:25:14.565202+00:00 [running]> on host 9f08a33860c2
[2023-07-27T03:30:31.126+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='richy' AIRFLOW_CTX_DAG_ID='dag_with_postgresv03' AIRFLOW_CTX_TASK_ID='get_s3_id' AIRFLOW_CTX_EXECUTION_DATE='2023-07-27T03:25:14.565202+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-27T03:25:14.565202+00:00'
[2023-07-27T03:30:31.127+0000] {s3.py:99} INFO - Poking for key : s3://minikubebucke/iris-dataset.csv
[2023-07-27T03:30:31.137+0000] {base.py:73} INFO - Using connection ID 'aws_conn' for task execution.
[2023-07-27T03:30:31.137+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='aws_conn', conn_type='aws') credentials retrieved from extra.
[2023-07-27T03:30:36.436+0000] {s3.py:99} INFO - Poking for key : s3://minikubebucke/iris-dataset.csv
[2023-07-27T03:30:41.476+0000] {s3.py:99} INFO - Poking for key : s3://minikubebucke/iris-dataset.csv
[2023-07-27T03:30:46.502+0000] {s3.py:99} INFO - Poking for key : s3://minikubebucke/iris-dataset.csv
[2023-07-27T03:30:51.532+0000] {s3.py:99} INFO - Poking for key : s3://minikubebucke/iris-dataset.csv
[2023-07-27T03:30:56.555+0000] {s3.py:99} INFO - Poking for key : s3://minikubebucke/iris-dataset.csv
[2023-07-27T03:31:01.577+0000] {s3.py:99} INFO - Poking for key : s3://minikubebucke/iris-dataset.csv
[2023-07-27T03:31:01.590+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 242, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 30.460963263998565 seconds exceeds the specified timeout of 30.
[2023-07-27T03:31:01.605+0000] {taskinstance.py:1350} INFO - Immediate failure requested. Marking task as FAILED. dag_id=dag_with_postgresv03, task_id=get_s3_id, execution_date=20230727T032514, start_date=20230727T033030, end_date=20230727T033101
[2023-07-27T03:31:01.615+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 18 for task get_s3_id (Sensor has timed out; run duration of 30.460963263998565 seconds exceeds the specified timeout of 30.; 225)
[2023-07-27T03:31:01.680+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-27T03:31:01.700+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
