[2023-07-27T03:25:15.304+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgresv03.get_s3_id manual__2023-07-27T03:25:14.565202+00:00 [queued]>
[2023-07-27T03:25:15.311+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgresv03.get_s3_id manual__2023-07-27T03:25:14.565202+00:00 [queued]>
[2023-07-27T03:25:15.312+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2023-07-27T03:25:15.320+0000] {taskinstance.py:1327} INFO - Executing <Task(S3KeySensor): get_s3_id> on 2023-07-27 03:25:14.565202+00:00
[2023-07-27T03:25:15.324+0000] {standard_task_runner.py:57} INFO - Started process 8075 to run task
[2023-07-27T03:25:15.328+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_postgresv03', 'get_s3_id', 'manual__2023-07-27T03:25:14.565202+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_dependency.py', '--cfg-path', '/tmp/tmpkx928b1d']
[2023-07-27T03:25:15.330+0000] {standard_task_runner.py:85} INFO - Job 16: Subtask get_s3_id
[2023-07-27T03:25:15.369+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_with_postgresv03.get_s3_id manual__2023-07-27T03:25:14.565202+00:00 [running]> on host 93edf6c77c0f
[2023-07-27T03:25:15.425+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='richy' AIRFLOW_CTX_DAG_ID='dag_with_postgresv03' AIRFLOW_CTX_TASK_ID='get_s3_id' AIRFLOW_CTX_EXECUTION_DATE='2023-07-27T03:25:14.565202+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-27T03:25:14.565202+00:00'
[2023-07-27T03:25:15.426+0000] {s3.py:99} INFO - Poking for key : s3://minikubebucke/iris-dataset.csv
[2023-07-27T03:25:15.435+0000] {base.py:73} INFO - Using connection ID 'aws_conn' for task execution.
[2023-07-27T03:25:15.437+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='aws_conn', conn_type='aws') credentials retrieved from extra.
[2023-07-27T03:25:20.709+0000] {s3.py:99} INFO - Poking for key : s3://minikubebucke/iris-dataset.csv
[2023-07-27T03:25:25.727+0000] {s3.py:99} INFO - Poking for key : s3://minikubebucke/iris-dataset.csv
[2023-07-27T03:25:30.757+0000] {s3.py:99} INFO - Poking for key : s3://minikubebucke/iris-dataset.csv
[2023-07-27T03:25:35.797+0000] {s3.py:99} INFO - Poking for key : s3://minikubebucke/iris-dataset.csv
[2023-07-27T03:25:40.826+0000] {s3.py:99} INFO - Poking for key : s3://minikubebucke/iris-dataset.csv
[2023-07-27T03:25:45.861+0000] {s3.py:99} INFO - Poking for key : s3://minikubebucke/iris-dataset.csv
[2023-07-27T03:25:45.883+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 242, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 30.45645688899822 seconds exceeds the specified timeout of 30.
[2023-07-27T03:25:45.903+0000] {taskinstance.py:1350} INFO - Immediate failure requested. Marking task as FAILED. dag_id=dag_with_postgresv03, task_id=get_s3_id, execution_date=20230727T032514, start_date=20230727T032515, end_date=20230727T032545
[2023-07-27T03:25:45.917+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 16 for task get_s3_id (Sensor has timed out; run duration of 30.45645688899822 seconds exceeds the specified timeout of 30.; 8075)
[2023-07-27T03:25:45.952+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-27T03:25:45.966+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
